//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package weka.core.expressionlanguage.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */ int TIMES = 11;
  int AND = 16;
  int IS = 24;
  int LT = 20;
  int PLUS = 9;
  int OR = 17;
  int RPAREN = 7;
  int EQUAL = 19;
  int DIVISION = 12;
  int NOT = 18;
  int IDENTIFIER = 2;
  int POW = 13;
  int GT = 22;
  int LPAREN = 6;
  int LE = 21;
  int REGEXP = 25;
  int BOOLEAN = 5;
  int STRING = 4;
  int COMMA = 8;
  int FLOAT = 3;
  int EOF = 0;
  int UPLUS = 15;
  int GE = 23;
  int MINUS = 10;
  int error = 1;
  int UMINUS = 14;
  String[] terminalNames = new String[] {
      "EOF", "error", "IDENTIFIER", "FLOAT", "STRING", "BOOLEAN", "LPAREN", "RPAREN", "COMMA",
      "PLUS", "MINUS", "TIMES", "DIVISION", "POW", "UMINUS", "UPLUS", "AND", "OR", "NOT", "EQUAL",
      "LT", "LE", "GT", "GE", "IS", "REGEXP"
  };
}

